steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        pwd
        ls -lrt
        sed -i 's/image_hash/$COMMIT_SHA/g' kubernetes/values.yaml
    id: pass image hash to values.yaml
    entrypoint: sh
  - name: us.gcr.io/hb-devops-case/helm
    id: Deploy chart
    args:
      - upgrade
      - -i
      - go-helloworld
      - ./kubernetes
      - -f
      - ./kubernetes/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
