steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        pwd
        ls -lrt
        sed -i 's/image_name/$COMMIT_SHA/g' kubernetes/values.yaml
        cat kubernetes/values.yaml
    id: pass image name to values.yaml
    entrypoint: sh
