
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld
  name: go-helloworld
  namespace: hb-devops-case
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-helloworld
    spec:
      containers:
        - image: gcr.io/hb-devops-case/github.com/bbandak/hello-world
          imagePullPolicy: IfNotPresent
          name: go-helloworld-sha256-1
